### ISSUE TITLE
unknown field 'DecodeCookie' in struct literal of type sessions.Config

### ISSUE THREAD

**Issue by yunhor** [kataras/go-sessions#10]
why no field DecodeCookie, I can find it in config.go
my code is 
	sess := sessions.New(sessions.Config{
		Cookie: model.Cfg.CookieName,
		//DecodeCookie:                false,
		Expires:                     time.Duration(model.Cfg.CookieDuration),
		CookieLength:                32,
		DisableSubdomainPersistence: false,
      )}
I commet the DecodeCookie field line,then pass build

**Comment by kataras** [comment]
`DecodeCookie` is there, you just have to upgrade your local $GOPATH.

`go get -u github.com/kataras/go-sessions`

**Comment by kataras** [comment]
`DecodeCookie` is there: https://github.com/kataras/go-sessions/blob/master/config.go#L41, you just have to upgrade your local $GOPATH.

`go get -u github.com/kataras/go-sessions`

**Comment by kataras** [comment]
`DecodeCookie` is there: https://github.com/kataras/go-sessions/blob/master/config.go#L41, you just have to upgrade your local $GOPATH.

`go get -u github.com/kataras/go-sessions` 

If you're talking about iris.v6, this was being removed because it didn't provide any protection, I added  `Encode` and `Decode` in order to use your own custom encoding or the popular "securecookie", 
check an example here: https://github.com/kataras/iris/blob/v6/_examples/intermediate/sessions/securecookie/main.go , you will love it :)

**Comment by kataras** [comment]
`DecodeCookie` is [there](https://github.com/kataras/go-sessions/blob/master/config.go#L41), you just have to upgrade your local $GOPATH with `go get -u github.com/kataras/go-sessions` 

------

If you're talking about **iris.v6**, this was removed as requested by a community member, [here](http://support.iris-go.com/d/29-mark-cookie-for-session-as-secure) because it didn't provide any protection, instead I added  `Encode` and `Decode` in order to use your own custom encoding or the popular "securecookie" for better security.
You can take a quick looka t the example, here: https://github.com/kataras/iris/blob/v6/_examples/intermediate/sessions/securecookie/main.go , you will love it :)

**Comment by kataras** [comment]
`DecodeCookie` is [there](https://github.com/kataras/go-sessions/blob/master/config.go#L41), you just have to upgrade your local $GOPATH with `go get -u github.com/kataras/go-sessions` 

------

If you're talking about **iris.v6**, this was removed as requested by a community member, [here](http://support.iris-go.com/d/29-mark-cookie-for-session-as-secure) because it didn't provide any protection, instead I added  `Encode` and `Decode` in order to use your own custom encoding or the popular "securecookie" for better security.
You can take a quick look at the example, here: https://github.com/kataras/iris/blob/v6/_examples/intermediate/sessions/securecookie/main.go , you will love it :)

**Comment by yunhor** [comment]
thank you kataras,I will try it
