### ISSUE TITLE
The SetFlash() function does not work

### ISSUE THREAD

**Issue by dxvgef** [kataras/go-sessions#7]
I use the redis storage engine, and execute `SetFlash("test", "ok")`, but I have not seen in the redis cookie and write the value, use `GetFlashString("test")` also does not read the value.

**Comment by kataras** [comment]
Hello @dxvgef ,

The session databases are not working with flash messages, this is a decision I took, it's by-design, because flash messages are useful for 'success/fail' messages, they are removed after the user uses them, so they are not useful to persistence on any sessiondb-store.

For `SetFlash` you were 50% correct, the `SetFlash` was working and `GetFlashes` also, the issue was on `GetFlash` which I fixed right now, I added a `DeleteFlash` method also :)

 Thanks for the report, you're the best!!
